### ISSUE TITLE
初始解问题

### ISSUE THREAD

**Issue by TimeGone07** [TimeGone07/VRPTW-ALNS#1]
生成初始解的贪心算法，原本是车辆最近的可行点进行插入，但考虑到这样会导致很多车队到达某一客户时会产生许多的等待时间，所以改成了能最快进行服务的可行点进行插入，改成这样之后，要不了几次迭代c101的算例就能找到最优解，但是在尝试其它算例的时候效果就没那么好了。然后发现这种方式的初始解如果找到了最小使用车辆就能通过alns找到最优解，如果用的车辆不是最优解，那在算法迭代中也很难实现车辆的减少。也就是说，我这个的结果和初始解关系很大，我知道这一点没问题，但我的算法很难使车辆减少，这一点我就不是很清楚了，从道理上说毕竟每次只破坏两三个节点，一个车好些个节点，想减少车辆确实还挺难的。这样的情况我如果想再做优化，就是需要再优化生成初始解的方式是吗？虽然说，这个课程作业可能优化结果差不多就行，但毕竟有的算例得出的结果能比最优解多30%，不过总体上平均差多少我还没有进行计算，所以我需要再进行计算来考虑我需不需要再做优化

**Comment by SmilingWayne** [comment]
倒也不一定。ToDo List:

1. 确定一下确实是车多了造成的；确认一下平均差距有多少，列个清单；
2. 试试算子Worst Case Removal? 
3. 找机会精简一下代码结构。写在一个.py 中debug难免有问题。参考 仓库：https://github.com/LingLi28/PDPTW

**Comment by TimeGone07** [comment]
我批量跑了一下，c10几的确实是车多了导致的，它的几个算例能跑到10个车的都找到最优解了，车多的成本差的就很多。然后对于其他的算例，整体结果确实不是很好，首先是很少有跑到最优解的，其次是有几个是最小车辆但距离最优解也有一定距离，整体上绝大部分都是找不到最少车辆，成本也比较高，平均比最优解高了30%，成本和车辆都是。我之前想的是车辆导致的确实是被c10几的算例给限制住了，有点一叶障目，确实算法本身的收敛也远远不够。这个算例我是跑了400次迭代（虽然和200估计也没啥区别），所以可能运行时间上不咋好看
[算例结果.xlsx](https://github.com/user-attachments/files/18099116/default.xlsx)


这个Worst Case Removal是和greedy removal相反的是吗，就是取破坏后成本节约最小的？我看那篇alns的论文，他的好像是用了一个参数控制这个的随机选择，可能选节约大的或小的。是加一个worst case还是改成论文那种参数控制，师兄你有明确的想法吗还是需要之前提到的固定随机数种子的数值实验来确认

**Comment by SmilingWayne** [comment]
1. 定种子 先让结果能复现
2. 我明天check一下具体结果和其他heuristic的结果，目前阶段不必过于追求最优解 想着怎么相比目前解有improve


---- Replied Message ----
| From | ***@***.***> |
| Date | 12/12/2024 00:31 |
| To | TimeGone07/VRPTW-ALNS ***@***.***> |
| Cc | SmilingWayne ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [TimeGone07/VRPTW-ALNS] 初始解问题 (Issue #1) |

我批量跑了一下，c10几的确实是车多了导致的，它的几个算例能跑到10个车的都找到最优解了，车多的成本差的就很多。然后对于其他的算例，整体结果确实不是很好，首先是很少有跑到最优解的，其次是有几个是最小车辆但距离最优解也有一定距离，整体上绝大部分都是找不到最少车辆，成本也比较高，平均比最优解高了30%，成本和车辆都是。我之前想的是车辆导致的确实是被c10几的算例给限制住了，有点一叶障目，确实算法本身的收敛也远远不够。
算例结果.xlsx

这个Worst Case Removal是和greedy removal相反的是吗，就是取破坏后成本节约最小的？我看那篇alns的论文，他的好像是用了一个参数控制这个的随机选择，可能选节约大的或小的。是加一个worst case还是改成论文那种参数控制，师兄你有明确的想法吗还是需要之前提到的固定随机数种子的数值实验来确认
